# Generated by Django 4.1.7 on 2023-04-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
